/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParallelFetchingDashboardWaterfallRouteImport } from './routes/parallel-fetching/dashboard.waterfall'
import { Route as ParallelFetchingDashboardSafeRouteImport } from './routes/parallel-fetching/dashboard.safe'
import { Route as ParallelFetchingDashboardParallelRouteImport } from './routes/parallel-fetching/dashboard.parallel'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelFetchingDashboardWaterfallRoute =
  ParallelFetchingDashboardWaterfallRouteImport.update({
    id: '/parallel-fetching/dashboard/waterfall',
    path: '/parallel-fetching/dashboard/waterfall',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParallelFetchingDashboardSafeRoute =
  ParallelFetchingDashboardSafeRouteImport.update({
    id: '/parallel-fetching/dashboard/safe',
    path: '/parallel-fetching/dashboard/safe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParallelFetchingDashboardParallelRoute =
  ParallelFetchingDashboardParallelRouteImport.update({
    id: '/parallel-fetching/dashboard/parallel',
    path: '/parallel-fetching/dashboard/parallel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parallel-fetching/dashboard/parallel': typeof ParallelFetchingDashboardParallelRoute
  '/parallel-fetching/dashboard/safe': typeof ParallelFetchingDashboardSafeRoute
  '/parallel-fetching/dashboard/waterfall': typeof ParallelFetchingDashboardWaterfallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parallel-fetching/dashboard/parallel': typeof ParallelFetchingDashboardParallelRoute
  '/parallel-fetching/dashboard/safe': typeof ParallelFetchingDashboardSafeRoute
  '/parallel-fetching/dashboard/waterfall': typeof ParallelFetchingDashboardWaterfallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/parallel-fetching/dashboard/parallel': typeof ParallelFetchingDashboardParallelRoute
  '/parallel-fetching/dashboard/safe': typeof ParallelFetchingDashboardSafeRoute
  '/parallel-fetching/dashboard/waterfall': typeof ParallelFetchingDashboardWaterfallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/parallel-fetching/dashboard/parallel'
    | '/parallel-fetching/dashboard/safe'
    | '/parallel-fetching/dashboard/waterfall'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/parallel-fetching/dashboard/parallel'
    | '/parallel-fetching/dashboard/safe'
    | '/parallel-fetching/dashboard/waterfall'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/parallel-fetching/dashboard/parallel'
    | '/parallel-fetching/dashboard/safe'
    | '/parallel-fetching/dashboard/waterfall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ParallelFetchingDashboardParallelRoute: typeof ParallelFetchingDashboardParallelRoute
  ParallelFetchingDashboardSafeRoute: typeof ParallelFetchingDashboardSafeRoute
  ParallelFetchingDashboardWaterfallRoute: typeof ParallelFetchingDashboardWaterfallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-fetching/dashboard/waterfall': {
      id: '/parallel-fetching/dashboard/waterfall'
      path: '/parallel-fetching/dashboard/waterfall'
      fullPath: '/parallel-fetching/dashboard/waterfall'
      preLoaderRoute: typeof ParallelFetchingDashboardWaterfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-fetching/dashboard/safe': {
      id: '/parallel-fetching/dashboard/safe'
      path: '/parallel-fetching/dashboard/safe'
      fullPath: '/parallel-fetching/dashboard/safe'
      preLoaderRoute: typeof ParallelFetchingDashboardSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-fetching/dashboard/parallel': {
      id: '/parallel-fetching/dashboard/parallel'
      path: '/parallel-fetching/dashboard/parallel'
      fullPath: '/parallel-fetching/dashboard/parallel'
      preLoaderRoute: typeof ParallelFetchingDashboardParallelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ParallelFetchingDashboardParallelRoute:
    ParallelFetchingDashboardParallelRoute,
  ParallelFetchingDashboardSafeRoute: ParallelFetchingDashboardSafeRoute,
  ParallelFetchingDashboardWaterfallRoute:
    ParallelFetchingDashboardWaterfallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
