/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokemonRouteImport } from './routes/pokemon'
import { Route as FavouriteRouteImport } from './routes/favourite'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FallbacksIndexRouteImport } from './routes/fallbacks/index'
import { Route as StreamingSsrProductUseRouteImport } from './routes/streaming-ssr/product-use'
import { Route as StreamingSsrProductRouteImport } from './routes/streaming-ssr/product'
import { Route as LoaderDepsEmployeesRouteImport } from './routes/loader-deps/employees'
import { Route as FallbacksAnalyticsRouteImport } from './routes/fallbacks/analytics'
import { Route as FallbacksReportsIndexRouteImport } from './routes/fallbacks/reports/index'
import { Route as ParallelFetchingDashboardWaterfallRouteImport } from './routes/parallel-fetching/dashboard.waterfall'
import { Route as ParallelFetchingDashboardSafeRouteImport } from './routes/parallel-fetching/dashboard.safe'
import { Route as ParallelFetchingDashboardParallelRouteImport } from './routes/parallel-fetching/dashboard.parallel'

const PokemonRoute = PokemonRouteImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouriteRoute = FavouriteRouteImport.update({
  id: '/favourite',
  path: '/favourite',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FallbacksIndexRoute = FallbacksIndexRouteImport.update({
  id: '/fallbacks/',
  path: '/fallbacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingSsrProductUseRoute = StreamingSsrProductUseRouteImport.update({
  id: '/streaming-ssr/product-use',
  path: '/streaming-ssr/product-use',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingSsrProductRoute = StreamingSsrProductRouteImport.update({
  id: '/streaming-ssr/product',
  path: '/streaming-ssr/product',
  getParentRoute: () => rootRouteImport,
} as any)
const LoaderDepsEmployeesRoute = LoaderDepsEmployeesRouteImport.update({
  id: '/loader-deps/employees',
  path: '/loader-deps/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FallbacksAnalyticsRoute = FallbacksAnalyticsRouteImport.update({
  id: '/fallbacks/analytics',
  path: '/fallbacks/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FallbacksReportsIndexRoute = FallbacksReportsIndexRouteImport.update({
  id: '/fallbacks/reports/',
  path: '/fallbacks/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelFetchingDashboardWaterfallRoute =
  ParallelFetchingDashboardWaterfallRouteImport.update({
    id: '/parallel-fetching/dashboard/waterfall',
    path: '/parallel-fetching/dashboard/waterfall',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParallelFetchingDashboardSafeRoute =
  ParallelFetchingDashboardSafeRouteImport.update({
    id: '/parallel-fetching/dashboard/safe',
    path: '/parallel-fetching/dashboard/safe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParallelFetchingDashboardParallelRoute =
  ParallelFetchingDashboardParallelRouteImport.update({
    id: '/parallel-fetching/dashboard/parallel',
    path: '/parallel-fetching/dashboard/parallel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favourite': typeof FavouriteRoute
  '/pokemon': typeof PokemonRoute
  '/fallbacks/analytics': typeof FallbacksAnalyticsRoute
  '/loader-deps/employees': typeof LoaderDepsEmployeesRoute
  '/streaming-ssr/product': typeof StreamingSsrProductRoute
  '/streaming-ssr/product-use': typeof StreamingSsrProductUseRoute
  '/fallbacks/': typeof FallbacksIndexRoute
  '/parallel-fetching/dashboard/parallel': typeof ParallelFetchingDashboardParallelRoute
  '/parallel-fetching/dashboard/safe': typeof ParallelFetchingDashboardSafeRoute
  '/parallel-fetching/dashboard/waterfall': typeof ParallelFetchingDashboardWaterfallRoute
  '/fallbacks/reports/': typeof FallbacksReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favourite': typeof FavouriteRoute
  '/pokemon': typeof PokemonRoute
  '/fallbacks/analytics': typeof FallbacksAnalyticsRoute
  '/loader-deps/employees': typeof LoaderDepsEmployeesRoute
  '/streaming-ssr/product': typeof StreamingSsrProductRoute
  '/streaming-ssr/product-use': typeof StreamingSsrProductUseRoute
  '/fallbacks': typeof FallbacksIndexRoute
  '/parallel-fetching/dashboard/parallel': typeof ParallelFetchingDashboardParallelRoute
  '/parallel-fetching/dashboard/safe': typeof ParallelFetchingDashboardSafeRoute
  '/parallel-fetching/dashboard/waterfall': typeof ParallelFetchingDashboardWaterfallRoute
  '/fallbacks/reports': typeof FallbacksReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/favourite': typeof FavouriteRoute
  '/pokemon': typeof PokemonRoute
  '/fallbacks/analytics': typeof FallbacksAnalyticsRoute
  '/loader-deps/employees': typeof LoaderDepsEmployeesRoute
  '/streaming-ssr/product': typeof StreamingSsrProductRoute
  '/streaming-ssr/product-use': typeof StreamingSsrProductUseRoute
  '/fallbacks/': typeof FallbacksIndexRoute
  '/parallel-fetching/dashboard/parallel': typeof ParallelFetchingDashboardParallelRoute
  '/parallel-fetching/dashboard/safe': typeof ParallelFetchingDashboardSafeRoute
  '/parallel-fetching/dashboard/waterfall': typeof ParallelFetchingDashboardWaterfallRoute
  '/fallbacks/reports/': typeof FallbacksReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/favourite'
    | '/pokemon'
    | '/fallbacks/analytics'
    | '/loader-deps/employees'
    | '/streaming-ssr/product'
    | '/streaming-ssr/product-use'
    | '/fallbacks/'
    | '/parallel-fetching/dashboard/parallel'
    | '/parallel-fetching/dashboard/safe'
    | '/parallel-fetching/dashboard/waterfall'
    | '/fallbacks/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/favourite'
    | '/pokemon'
    | '/fallbacks/analytics'
    | '/loader-deps/employees'
    | '/streaming-ssr/product'
    | '/streaming-ssr/product-use'
    | '/fallbacks'
    | '/parallel-fetching/dashboard/parallel'
    | '/parallel-fetching/dashboard/safe'
    | '/parallel-fetching/dashboard/waterfall'
    | '/fallbacks/reports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/favourite'
    | '/pokemon'
    | '/fallbacks/analytics'
    | '/loader-deps/employees'
    | '/streaming-ssr/product'
    | '/streaming-ssr/product-use'
    | '/fallbacks/'
    | '/parallel-fetching/dashboard/parallel'
    | '/parallel-fetching/dashboard/safe'
    | '/parallel-fetching/dashboard/waterfall'
    | '/fallbacks/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FavouriteRoute: typeof FavouriteRoute
  PokemonRoute: typeof PokemonRoute
  FallbacksAnalyticsRoute: typeof FallbacksAnalyticsRoute
  LoaderDepsEmployeesRoute: typeof LoaderDepsEmployeesRoute
  StreamingSsrProductRoute: typeof StreamingSsrProductRoute
  StreamingSsrProductUseRoute: typeof StreamingSsrProductUseRoute
  FallbacksIndexRoute: typeof FallbacksIndexRoute
  ParallelFetchingDashboardParallelRoute: typeof ParallelFetchingDashboardParallelRoute
  ParallelFetchingDashboardSafeRoute: typeof ParallelFetchingDashboardSafeRoute
  ParallelFetchingDashboardWaterfallRoute: typeof ParallelFetchingDashboardWaterfallRoute
  FallbacksReportsIndexRoute: typeof FallbacksReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemon': {
      id: '/pokemon'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourite': {
      id: '/favourite'
      path: '/favourite'
      fullPath: '/favourite'
      preLoaderRoute: typeof FavouriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallbacks/': {
      id: '/fallbacks/'
      path: '/fallbacks'
      fullPath: '/fallbacks/'
      preLoaderRoute: typeof FallbacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming-ssr/product-use': {
      id: '/streaming-ssr/product-use'
      path: '/streaming-ssr/product-use'
      fullPath: '/streaming-ssr/product-use'
      preLoaderRoute: typeof StreamingSsrProductUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming-ssr/product': {
      id: '/streaming-ssr/product'
      path: '/streaming-ssr/product'
      fullPath: '/streaming-ssr/product'
      preLoaderRoute: typeof StreamingSsrProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loader-deps/employees': {
      id: '/loader-deps/employees'
      path: '/loader-deps/employees'
      fullPath: '/loader-deps/employees'
      preLoaderRoute: typeof LoaderDepsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallbacks/analytics': {
      id: '/fallbacks/analytics'
      path: '/fallbacks/analytics'
      fullPath: '/fallbacks/analytics'
      preLoaderRoute: typeof FallbacksAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallbacks/reports/': {
      id: '/fallbacks/reports/'
      path: '/fallbacks/reports'
      fullPath: '/fallbacks/reports/'
      preLoaderRoute: typeof FallbacksReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-fetching/dashboard/waterfall': {
      id: '/parallel-fetching/dashboard/waterfall'
      path: '/parallel-fetching/dashboard/waterfall'
      fullPath: '/parallel-fetching/dashboard/waterfall'
      preLoaderRoute: typeof ParallelFetchingDashboardWaterfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-fetching/dashboard/safe': {
      id: '/parallel-fetching/dashboard/safe'
      path: '/parallel-fetching/dashboard/safe'
      fullPath: '/parallel-fetching/dashboard/safe'
      preLoaderRoute: typeof ParallelFetchingDashboardSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-fetching/dashboard/parallel': {
      id: '/parallel-fetching/dashboard/parallel'
      path: '/parallel-fetching/dashboard/parallel'
      fullPath: '/parallel-fetching/dashboard/parallel'
      preLoaderRoute: typeof ParallelFetchingDashboardParallelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FavouriteRoute: FavouriteRoute,
  PokemonRoute: PokemonRoute,
  FallbacksAnalyticsRoute: FallbacksAnalyticsRoute,
  LoaderDepsEmployeesRoute: LoaderDepsEmployeesRoute,
  StreamingSsrProductRoute: StreamingSsrProductRoute,
  StreamingSsrProductUseRoute: StreamingSsrProductUseRoute,
  FallbacksIndexRoute: FallbacksIndexRoute,
  ParallelFetchingDashboardParallelRoute:
    ParallelFetchingDashboardParallelRoute,
  ParallelFetchingDashboardSafeRoute: ParallelFetchingDashboardSafeRoute,
  ParallelFetchingDashboardWaterfallRoute:
    ParallelFetchingDashboardWaterfallRoute,
  FallbacksReportsIndexRoute: FallbacksReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
